data:
  class_path: pl_modules.InferenceDataModule
  init_args:
    slice_dataset: data.CmrxReconInferenceSliceDataset
    # 1. Change D:/ to /mnt/d/
    data_path: /media/sbme26-600k/bitlocker_mount/CardiacCreed/cmrxrecon2023/ChallengeData/MultiCoil/Cine/TrainingSet/Subset30Acc8Acc10

    challenge: multicoil
    test_transform:
      class_path: data.CmrxReconDataTransform
      init_args:
        mask_func: null
        uniform_resolution: null
        mask_type: 'cartesian'
        test_num_low_frequencies: -1
    num_adj_slices: &n_adj_slc 5
    batch_size: 1
    distributed_sampler: true 
    test_filter:
      class_path: data.FuncFilterString
      init_args:
        # 2. Use a unique substring rather than the absolute path
        filter_str: "AccFactor08"
# dataset specific settings
seed_everything: 42
trainer:
  accelerator: gpu
  strategy: ddp
  devices: 1
  num_nodes: 1
  logger: false
  callbacks:
    -
      class_path: __main__.CustomWriter
      init_args:
        output_dir: /media/sbme26-600k/bitlocker_mount/CardiacCreed/ReconstructionOutput/PromptMRPlusCMR23Test
        write_interval: batch_and_epoch
# model:

ckpt_path: weights/cmr24-cardiac/promptmr-plus-epoch=11-step=337764.ckpt